### ISSUE TITLE
Missing inline symbols because of wrong SYMBOLSET path handling.

### ISSUE THREAD

**Issue by MaklariAgoston** [DMS-Aus/MapManager#22] opened 2016-09-20 12:47 UTC
If you edit the map file with Notepad++ and save it after setting the SYMBOLSET path relative to the map file.
(That is there is not a symbol file in the folder of the exe)

Open the map file in Map Manager and you will see that the inline symbols are not loaded. 
If someone saves the map file (no noticing that the file was wrongly loaded) than he will lose all his inline symbol definitions.

**Comment by szekerest** [comment] 2016-11-04 11:45
I couldn't reproduce this behaviour. As soon as the loading of the map fails, the raw map file text is loaded  to the text tab for manual editing, which contains the inline symbols.

**Comment by szekerest** [comment] 2022-03-04 19:18
The related issue has been fixed, closing

**Closed as completed by szekerest** 2022-03-04 19:18 UTC
